/usr/sbin/oracleasm createdisk VOL1  /dev/sdb1
/usr/sbin/oracleasm createdisk VOL2  /dev/sdb2
/usr/sbin/oracleasm createdisk VOL3  /dev/sdb3
/usr/sbin/oracleasm createdisk VOL4  /dev/sdb5
/usr/sbin/oracleasm createdisk VOL5  /dev/sdb6
/usr/sbin/oracleasm createdisk VOL6  /dev/sdb7
/usr/sbin/oracleasm createdisk VOL7  /dev/sdb8
/usr/sbin/oracleasm createdisk VOL8  /dev/sdb9
/usr/sbin/oracleasm createdisk VOL9  /dev/sdb10
/usr/sbin/oracleasm createdisk VOL10 /dev/sdb11
/usr/sbin/oracleasm createdisk VOL11 /dev/sdc1
/usr/sbin/oracleasm createdisk VOL12 /dev/sdc2
/usr/sbin/oracleasm createdisk VOL13 /dev/sdc3
/usr/sbin/oracleasm createdisk VOL14 /dev/sdc5
/usr/sbin/oracleasm createdisk VOL15 /dev/sdc6
