/usr/sbin/oracleasm deletedisk VOL1
/usr/sbin/oracleasm deletedisk VOL2
/usr/sbin/oracleasm deletedisk VOL3
/usr/sbin/oracleasm deletedisk VOL4
/usr/sbin/oracleasm deletedisk VOL5
/usr/sbin/oracleasm deletedisk VOL6
/usr/sbin/oracleasm deletedisk VOL7
/usr/sbin/oracleasm deletedisk VOL8
/usr/sbin/oracleasm deletedisk VOL9
/usr/sbin/oracleasm deletedisk VOL10
/usr/sbin/oracleasm deletedisk VOL11
/usr/sbin/oracleasm deletedisk VOL12
/usr/sbin/oracleasm deletedisk VOL13
/usr/sbin/oracleasm deletedisk VOL14
/usr/sbin/oracleasm deletedisk VOL15
