#!/bin/bash

for i in `awk '{print $1}' iplist05on`
do
    y=`awk /${i}/'{print $2}' iplist05on`
    z=`awk /${i}/'{print $3}' iplist05on`
    #echo "${i}|${y}|${z}"
    ./expect.sh ${i} ${y} ${z}
done
